jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
        id-token: write
        - name: Install cosign
        uses: sigstore/cosign-installer@main



